[env]
platform = atmelavr
board = pro8MHzatmega328
framework = arduino
upload_protocol = arduino
upload_speed = 57600   

[env:ultrasonic]
build_src_filter = +<main.cpp>

lib_deps =
    mysensors/MySensors

monitor_speed = 115200 

[env:counter]
build_src_filter = +<counter.cpp>

monitor_speed = 9600

[env:arduino_isp]
platform = atmelavr
board = uno
framework = arduino

build_src_filter = +<arduino_isp.cpp>
